### ISSUE TITLE
Quiet Period is corrupted when editing a build configuration

### ISSUE THREAD

**Issue by RochaStratovan** [jenkinsci/tikal-multijob-plugin#209] opened 2020-07-29 20:54 UTC
The multijob "Quiet period calculator" field gets corrupted (changed) when editing an unrelated field in the build configuration.

This issue is easy to reproduce.

1. Add a multijob job/build, set the _quiet period_ to 0 and save it
1. Edit the jobs configuration, change the description and save it

At this point the _quiet period_ has been corrupted/changed from 0 to `index < 5 ? 0 : 2 * 60`

This is a critical issue because modifying something completely unrelated to the quiet period, suh as it's description, causes the quiet period to change which in turn causes the jobs overall functionality to change.

**Comment by anoymouserver** [comment] 2020-09-11 08:39
possible duplicate of #200

**Comment by RochaStratovan** [comment] 2020-10-21 17:44
Any ETA on when this corruption issue will be resolved? It's been 3 months for this issue, which is pretty big.

**Comment by yorammi** [comment] 2020-12-29 19:18
duplicate with #200. A fixed released in 1.36

**Closed by yorammi** 2020-12-29 19:18 UTC
